server:
  port: 9608

## 服务名称
spring:
  application:
    name: dove-processing-service

  ## 文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB #单个文件上传大小
      max-request-size: 200MB #连续上传文件大小

  ## 服务注册发现
  cloud:
    nacos:
      discovery:
        #        server-addr: localhost:8848
        server-addr: 120.77.156.205:8848
        ip: 120.77.156.205
  ## 数据源配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.0.0.1:3306/pigeon_cloud_processing?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #    url: jdbc:mysql://localhost:3306/dove_cloud_processing?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
        password: root
#    password: cnjson!@#456
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 120.77.156.205
    port: 6666
    password: 711711711.com
    database: 15
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 5
        max-idle: 5
        min-idle: 0

## mp的xml扫描
mybatis-plus:
  mapper-locations: classpath:com/pigeon/processing/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

