server:
  port: 9804

spring:
  application:
    name: pigeon-breed-service

  profiles:
    active: dev

    ## 服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 39.99.247.58:8848
        ip: 39.99.247.58

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.156.205:3306/dove_cloud_farming2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: cnjson!@#456
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

  redis:
    host: 120.77.156.205
    port: 6666
    password: 711711711.com
    database: 14
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 5
        max-idle: 5
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:com/dove/breed/mapper/xml/*.xml  #默认就是任意mapper下的xml文件下的*xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

dove:
  thread:
    pool:
      core-pool-size: 3
      maxinum-pool-size: 5
      keep-alive-time: 18000


BASE_UI_URL:
  country: D:\\桌面\json文件\\国家图\\
  province: D:\\桌面\json文件\\省份图\\
  city: D:\\桌面\json文件\\梅州图\\
  companyIntroduction: D:\\桌面\json文件\\金绿公司整体介绍图\\